apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db-pooler
  labels:
    app: db-pooler
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: db-pooler
    spec:
      containers:
        - name: pgbouncer
          image: eu.gcr.io/mimir-185212/pgbouncer:1.8.1
          ports:
            - name: svc-port
              containerPort: 5432
          env:
            - name: DB_HOST
              value: mimir-db
          volumeMounts:
            - name: userlist
              mountPath: /etc/pgbouncer/userlist.txt
              subPath: userlist.txt
              readOnly: true
            - name: pgbouncer-config
              mountPath: /etc/pgbouncer/pgbouncer.ini
              subPath: pgbouncer.ini
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: svc-port
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: svc-port
            initialDelaySeconds: 20
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                # Allow existing queries clients to complete within 120 seconds
                command: ["/bin/sh", "-c", "killall -INT pgbouncer && sleep 120"]
          imagePullPolicy: Always
      volumes:
        - name: userlist
          secret:
            secretName: db-credentials
            items:
              - key: dbpool.userlist
                path: userlist.txt
        - name: pgbouncer-config
          configMap:
            name: pgbouncer-config
            items:
              - key: pgbouncer.ini
                path: pgbouncer.ini
      imagePullSecrets:
        - name: gcr-json-key
