apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: message-queue
  labels:
    app: message-queue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: message-queue
    spec:
      containers:
      - name: message-queue
        image: eu.gcr.io/mimir-185212/message-queue:1.1
        ports:
        - name: amqp-port
          containerPort: 5672
        - name: management-port
          containerPort: 15672
        volumeMounts:
        - mountPath: /var/lib/rabbitmq/mnesia
          name:  mq-volume
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "node_health_check", "-t", "3"]
          initialDelaySeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "node_health_check", "-t", "3"]
          initialDelaySeconds: 30
          timeoutSeconds: 3
        resources:
          requests:
            memory: 200Mi
            cpu: "200m"
          limits:
            memory: 200Mi
            cpu: "200m"
      volumes:
      - name: mq-volume
        persistentVolumeClaim:
          claimName: mq-pvc
      imagePullSecrets:
      - name: gcr-json-key
