apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: message-queue
  labels:
    app: message-queue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: message-queue
    spec:
      containers:
      - name: spam-filter
        image: eu.gcr.io/mimir-185212/message-queue:1.0
        ports:
        - name: amqp-port
          containerPort: 5672
        - name: management-port
          containerPort: 15672
        volumeMounts:
        - mountPath: /var/lib/rabbitmqctl/data
          name:  mq-volume
        livenessProbe:
          exec:
            command: ["rabbitmqctl" "node_health_check" "-t" "3"]
          initialDelaySeconds: 120
          timeoutSeconds: 3
        readinessProbe:
          exec:
            command: ["rabbitmqctl" "node_health_check" "-t" "3"]
          initialDelaySeconds: 120
          timeoutSeconds: 3
      volumes:
      - name: mq-volume
        persistentVolumeClaim:
          claimName: mq-vol-claim
