apiVersion: v1
kind: PersistentVolume
metadata:
  name: mq-vol
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mq-volume/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq-vol-claim
  namespace: mimir
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
