apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq-pvc
  namespace: mimir
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
